### PR TITLE
add fair random number generator

### PR DESCRIPTION
**Pull request by NiekAukes**
new rng to prevent the same sound playing twice in a row, and making it more likely less played sounds get a chance as well

### CODE REVIEW

**Comment by Orange-Murker** [comment]
Thanks for the pull request!

CircuitPython does not have the `Random` class in `random`

Please refer to the [official documentation](https://docs.circuitpython.org/en/latest/shared-bindings/random/index.html) to see everything that is available.

**Comment by Orange-Murker** [comment]
Would also be nice if you could place all your changes in `code.py` instead of making multiple files to keep the documentation consistent and to make deploying easier.

**Comment by NiekAukes** [comment]
I made changes according to your comments

**Comment by Orange-Murker** [comment]
Thanks. LGTM.

**Pull request merged**
